eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:9001/eureka

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    slave-list:
      - name: slave-1
        url: 
      - name: slave-2
        url: 
    username: 
    password: 
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    slave-list:
      - name: slave-1
        url:
      - name: slave-2
        url:
    username:
    password: 

gateway:
  ip: 172.18.0.254
