eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create
