server:
  port: 0 # Eureka 로부터 자동 포트 부여

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: product-service

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

gateway:
  ip: 172.18.0.254
